#!/usr/bin/env bash
# A Bash script that loops infinitely and handles the SIGTERM signal gracefully

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done
