#!/bin/bash

# Trap the SIGTERM signal and print a message instead of terminating
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop that prints a message every 2 seconds
while true
do
    echo "To infinity and beyond"
    sleep 2
done
